# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e1e0c0bbb1a2f90652656214811262f01afd79df9432b4d8038133a976f216187a154cba057db5e9338d99104c814cd91f19ffc2ee2a1ec02c5e6c50043894c

test:
  secret_key_base: 5f57496c7fd6d2b1b3a155d6eb44f9769c4f50f894f272e358488a712ea53bacea5f1796896aebafd417add37177e03f01580461fede9087a619b78750913c8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
